### PR TITLE
add simplified chinese translation for README;

### PR DESCRIPTION
**Pull request by zamia**
README is great for learn decorator/drapper, so I translate it to Simplified Chinese(简体中文) for chinese users;

### CODE REVIEW

**Comment by seanlinsley** [comment]
Thank you so much for translating the readme. One problem is it will be hard to keep the English and Chinese versions in sync. I'm not sure how we could manage that.

**Comment by codebycliff** [comment]
While I hate to close a pull request that adds translation, I agree with Sean's concerns about keeping it up to date. I'm not sure how we would could manage this well either. I'm going to close this for the time being; however, if you have suggestions on how to keep it up to date or feel strongly that it should be added, please let me know and I'd be happy to revisit this conversation.

**Comment by varyonic** [comment]
Wiki maybe?

**Comment by codebycliff** [comment]
Yes, absolutely. That was my first thought, but was unsure because it still suffers from the same problem of keeping up to date.

@zamia I have added your translation to the wiki [here](https://github.com/drapergem/draper/wiki/README-(Simplified-Chinese-Translation)).

**Pull request closed without merging**
