### PR TITLE
Add SimpleCov for code coverage analysis

### PR DESCRIPTION
**Pull request by debbbbie**
1. Add gem `simplecov`
2. move rake test `integration:all` to `integration/integration_spec.rb`

### CODE REVIEW

**Comment by codebycliff** [comment]
Would you be interested in fixing the conflicts on this?

**Comment by tibbon** [comment]
@debbbbie Still interested in this? I think it's a good idea!

**Comment by debbbbie** [comment]
@tibbon Sorry for delay, I'll resolve conflicts.

Thanks for reply

**Comment by debbbbie** [comment]
@codebycliff Sorry for the delay, I'll do it this day.

**Comment by codebycliff** [comment]
No worries! After re-reading my comment, it reads a little harsh. I definitely didn't intend that, I was just in a hurry. I definitely don't expect you to take care of it right away. I'll give it a couple weeks before I take any action.

**Comment by debbbbie** [comment]
@codebycliff Thanks for giving more time. 
I redo the `simplecov`, new pull-request is https://github.com/drapergem/draper/pull/851

**Pull request closed without merging**
