### PR TITLE
update rspec syntax to the new one

### PR DESCRIPTION
**Pull request by lucianosousa**

### CODE REVIEW

**Comment by seanlinsley** [comment]
Thanks for the PR! After #752 is merged, we'll see if the test suite still passes with this change.

**Comment by seanlinsley** [comment]
@lucianosousa can you rebase this on master?

**Comment by lucianosousa** [comment]
@seanlinsley done

**Comment by MrEmelianenko** [comment]
@lucianosousa Thank you for your work! :thumbsup: :thumbsup: :thumbsup:

@seanlinsley So, I think we can merge it. Also, Sean, we need to review all old branches and merge/remove they.

**Comment by seanlinsley** [comment]
@MrEmelianenko I've already been reviewing old PRs, and have closed some. Feel free to help review them.

**Pull request merged**
