### PR TITLE
Nail down version

### PR DESCRIPTION
**Pull request by kbrock**
Trying to get draper green again

Last passing build is https://travis-ci.org/drapergem/draper/jobs/94943640
Current build is: https://travis-ci.org/drapergem/draper/jobs/134645121

Trying to nail down gems to get the build working

### CODE REVIEW

**Comment by seanlinsley** [comment]
```
Bundler could not find compatible versions for gem "minitest":
  In Gemfile:
    rails (~> 4.2.0) ruby depends on
      activesupport (= 4.2.3) ruby depends on
        minitest (~> 5.1) ruby
    minitest-rails (~> 1.0.0) ruby depends on
      minitest (4.7.0)

Bundler could not find compatible versions for gem "railties":
  In Gemfile:
    minitest-rails (~> 1.0.0) ruby depends on
      railties (< 4.1, >= 3.0) ruby
    rails (~> 4.2.0) ruby depends on
      railties (4.2.0)
```

**Comment by seanlinsley** [comment]
Also this: (only for Rails 4.0 oddly)
```
capybara-2.5.0/lib/capybara/rails.rb:15:in `<top (required)>': undefined method `join' for nil:NilClass (NoMethodError)
  from activesupport-4.0.13/lib/active_support/dependencies.rb:229:in `require'
  from activesupport-4.0.13/lib/active_support/dependencies.rb:229:in `block in require'
  from activesupport-4.0.13/lib/active_support/dependencies.rb:214:in `load_dependency'
  from activesupport-4.0.13/lib/active_support/dependencies.rb:229:in `require'
  from rspec-rails-3.2.3/lib/rspec/rails/vendor/capybara.rb:7:in `<top (required)>'
  from activesupport-4.0.13/lib/active_support/dependencies.rb:229:in `require'
  from activesupport-4.0.13/lib/active_support/dependencies.rb:229:in `block in require'
  from activesupport-4.0.13/lib/active_support/dependencies.rb:214:in `load_dependency'
  from activesupport-4.0.13/lib/active_support/dependencies.rb:229:in `require'
  from rspec-rails-3.2.3/lib/rspec/rails.rb:13:in `<top (required)>'
  from ammeter-1.1.3/lib/ammeter/init.rb:2:in `require'
```

**Comment by seanlinsley** [comment]
In #752 I have the test suite passing, so I'm going to close this PR. Thanks for the effort nonetheless 😄

**Comment by kbrock** [comment]
@seanlinsley thanks for doing a great job here

**Pull request closed without merging**
