### PR TITLE
Remove ruby 2.7 deprecation

### PR DESCRIPTION
**Pull request by badlamer**
## Description
Remove ruby 2.7 deprecation
```
lib/ruby/gems/2.7.0/gems/draper-3.1.0/lib/draper/delegation.rb:10: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
```
Detail your changes here.  
A few sentences describing the overall goals of the pull request's commits will suffice.
Some questions you might answer:

## References
* [GitHub Issue 869](https://github.com/drapergem/draper/issues/869)

### CODE REVIEW

**Comment by mberlanda** [comment]
hey @codebycliff , would it be possible to bump a minor version with this deprecation warning fixed ? Thanks a lot!

**Comment by codebycliff** [comment]
Unfortunately there are breaking changes in `master` so a quick minor version release won't be possible. I'm hoping to cut a new version in the coming weeks.

**Comment by swistaczek** [comment]
Hey, any chance that you know release date @codebycliff :)?

**Comment by codebycliff** [comment]
I just got version 4.0.0 released this morning. Please let me know if you have any issues with it.

**Pull request merged**
