### PR TITLE
Rspec3 Update - Spec Syntax, Generators, and Monkey-Patching

### PR DESCRIPTION
**Pull request by baberthal**
## Update to latest RSpec (3.3)

As of rspec-rails 3.3 generates two files:
- spec/spec_helper.rb
- spec/rails_helper.rb

This allows the user to either do pure ruby unit tests or include the entire
rails environment. Draper really only works in a rails application if it has the
rails environment. This matches ~> 3.3 and uses the rails_helper instead of
spec_helper for the dummy app specs, but the standard spec_helper for
the draper specs, so the entire suite doesn't depend on loading rails.

Fix Spec spec generator because RSpec no longer prefers
monkey-patching. Refactor PR #675 to be more concise re RSpec Version
check, and to use RSpec::Core::Version rather than
RSpec::Rails::Version, in case the latter does not exist.
## Updated all specs to RSpec 3.0 syntax

Change specs to use synax `expect(OBJECT).to EXPECTATION` rather that
`OBJECT.should`. Changed all `OBJECT.stub(METHOD)` to `allow(OBJECT).to
receive(:method)`

Change one-liners to use syntax: `it { is_expected.to XXX }` rather than
`it { should }`.

Merge PR #674 from @mcasper and fix all trivial conflicts (i.e
`allow(OBJ).to receive(:message)` vs `allow(OBJ).to receive_messages`)
## Gitignore

Ignore .ruby_version, .ruby_gemset, any rspec_output, and any generated binstubs.
## Spec Helper

ActiveRecord::Migration.maintain_test_schema! is undefined in Rails
4.0, so I made that method conditional upon ENV['RAILS_VERSION'].

Explicitly disable monkey_patching, in addition to some trivial edits related to the RSpec upgrade.
## Notes

All the specs pass, although one of the generator specs throws an uninitialized constant RSpec::Support::Differ error. This appears to happen both on travis on on my local machine. I believe it is related to https://github.com/alexrothenberg/ammeter/issues/48, but I can't be sure. Let me know what you guys think and I'll see what I can do to fix it.

### CODE REVIEW

**Comment by lucianosousa** [comment]
Nice job! Congrats.

Hope @jcasimir merge this soon as possible.

**Comment by krainboltgreene** [comment]
Any update on either this or my pull request?

**Comment by mroach** [comment]
Is there any reason why this wasn't merged? I was going to submit a PR addressing this exact issue. The default spec templates generated by draper are not compatible with proper RSpec 3 configuration.

**Comment by codebycliff** [comment]
@baberthal Sorry we are just now getting back to you. Would you be interested in fixing the conflicts on this? I'd be happy to merge it once you do.

**Comment by baberthal** [comment]
@codebycliff I'd be happy to. I probably won't be able to get to it until this weekend at the earliest. That work?

**Comment by codebycliff** [comment]
Yes, absolutely. Thanks!

**Comment by codebycliff** [comment]
Although it looks like a lot of these changes were merged with https://github.com/drapergem/draper/pull/746. There still stuff to do (e.g. `describe` -> `RSpec.describe`), but not near as much.

Also, would you mind pulling out the stuff not related to syntax changes (e.g. the addition of guard) into another pull request? It will make it much easier to track changes.

**Comment by codebycliff** [comment]
Are you still interested in fixing these conflicts?

**Comment by codebycliff** [comment]
@tibbon Are you interested in taking this over? If not, I'll probably close this pull request and try to get to it myself at a later date.

**Comment by codebycliff** [comment]
A lot of what is in this pull request has already been merged. That being said, there are still some things in here that I'd like to get through, so here is what I'm going to do: 

1. Branch off of this branch (https://github.com/drapergem/draper/pull/853)
1. Fix the conflicts
1. Revert any non-related changes
1. Merge it

Let me know if you have any issue with this. The new pull request can be found here: https://github.com/drapergem/draper/pull/853

**Pull request closed without merging**
