### PR TITLE
Add projections for rails-vim

### PR DESCRIPTION
**Pull request by eloyesp**
Add projections.json to make [vim-rails](https://github.com/tpope/vim-rails) know about decorators.

### CODE REVIEW

**Comment by seanlinsley** [comment]
What does this file do, exactly? What are projections?

**Comment by eloyesp** [comment]
Projections are a way to make vim-rails (or any IDE capable of reading the file) about the project making possible to navigate between related files, running the right tests and knowing the existing words.

**Comment by eloyesp** [comment]
Any news about this?

**Comment by codebycliff** [comment]
@eloyesp Thanks for the contribution and sorry it took so long to get back to you. I don't feel like editor specific code belongs in the actual library. I was willing to look past my opinion if any other major gems are doing this; however, it doesn't seem to be a standard practice. What I did do though is add a wiki page with your example [here](https://github.com/drapergem/draper/wiki/Projections-for-rails.vim). This wiki page also includes a link to a Thoughtbot article explaining various ways to set this up.

**Pull request closed without merging**
