### PR TITLE
Fix warnings with recent versions of `thor`

### PR DESCRIPTION
**Pull request by deivid-rodriguez**
I also clarified installation instructions in `README.md`.

### CODE REVIEW

**Comment by seanlinsley** [comment]
Thanks 😄 

BTW, in the future it'd be really useful to include links to stuff that's relevant to the changes. In this case you likely already had the Thor changelog open in your browser, so you have the ability to save maintainers the trouble of trying to locate that to verify your changes.

**Comment by deivid-rodriguez** [comment]
Mmmm is the link to the Thor issue and the copy of the warning not enough? :S

**Comment by deivid-rodriguez** [comment]
I didn't read the Thor change log BTW. I think the best way to verify a warning fix is to actually run the code before and after the change. That's why I fixed the generator tests for you :wink:

**Comment by seanlinsley** [comment]
>I think the best way to verify a warning fix is to actually run the code before and after the change. That's why I fixed the generator tests for you :wink:

Yeah because maintainers can afford 10+ minutes to review each individual PR 😛, and on a computer as opposed to a mobile device (likely adding 10 minutes to switch devices).

If it's not fixed yet, we should definitely update the test suite to fail on deprecations when running `rails generate`

>Mmmm is the link to the Thor issue and the copy of the warning not enough? :S

I actually didn't see your extended commit description before now, and I myself struggle with having my peers read commit descriptions. I usually decide to do one of these:

- copy/paste the text from the commits into the PR description
- mention in the PR description that the commit messages are particularly important

It's not your fault, it's GitHub's fault for hiding important information behind a tiny ellipsis.

**Comment by deivid-rodriguez** [comment]
Never got to answer here.

> If it's not fixed yet, we should definitely update the test suite to fail on deprecations when running rails generate

It is fixed, I just don't remember if the warnings were originally displayed by the test suite or not. I briefly looked into adding a test for this, but I didn't see a straight forward way to check error messages with `ammeter`, so I moved on.

> I actually didn't see your extended commit description before now, and I myself struggle with having my peers read commit descriptions. I usually decide to do one of these:
> * copy/paste the text from the commits into the PR description
> * mention in the PR description that the commit messages are particularly important

I personally don't merge PR's without reading full commit messages, but I'll try to adapt to your practices when/if I contribute to this repo again.

> Really, GitHub should update their UI to not hide important information behind a tiny ellipsis.

I think GitHub's UI is fine, to each his own.

**Pull request merged**
