### PR TITLE
Replace double quotes with single quotes

### PR DESCRIPTION
**Pull request by DmytroStepaniuk**
# Proposal request

## Description

I have noticed that some of string constants wrapped in double quotes, and some of them - in single quotes, so, my proposal is - use one approach to specify string constants and don't mix them.

## Things to discuss 

Double quotes vs single - which approach has better performance?

Example: 

https://github.com/vigetlabs/ruby-string-showdown

### CODE REVIEW

**Comment by DmytroStepaniuk** [comment]
Detected problems with newest minitest 5.10.2  (was 5.10.1)

**Comment by codebycliff** [comment]
Looks like rails fixed the bug [here](https://github.com/rails/rails/pull/29022) and it made it into the most recent release. So the builds are passing again 🎉 .

As far as the single quotes vs double quotes:

Single quotes are my preference, as well as the recommendation from the [Ruby Style Guide](https://github.com/bbatsov/ruby-style-guide) (hence Rubocop). I added Rubocop to the project a bit ago, but added an exception for string literals since there were so many. If you want to remove that configuration from `.rubocop.yml` and run rubocop to double check all usages have been fixed, I'd be happy to merge this. Thanks!

**Comment by Tonkpils** [comment]
> as well as the recommendation from the Ruby Style Guide

Actually, they use the single quotes in the style guide but they don't recommend one or the other.

From https://github.com/bbatsov/ruby-style-guide#strings

> Adopt a consistent string literal quoting style. There are two popular styles in the Ruby community, both of which are considered good

As far as performance is concerned:
https://stackoverflow.com/questions/1836467/is-there-a-performance-gain-in-using-single-quotes-vs-double-quotes-in-ruby/1836838#1836838

The performance difference is negligible pretty much

**Comment by DmytroStepaniuk** [comment]
Okay, updated,  `rubocop --only Style/StringLiterals` shows no Style/StringLiterals warnings!

**Comment by codebycliff** [comment]
Sorry it's taking me so long to get around to this. Can you also remove the configuration from `.rubocop.yml` so that this change makes it into the build?

**Comment by codebycliff** [comment]
@DmytroStepaniuk @tibbon Are either of you interested in getting this pull request up to date? If not, I'll probably close it and take care of it myself at a later date.

**Comment by DmytroStepaniuk** [comment]
> @DmytroStepaniuk @tibbon Are either of you interested in getting this pull request up to date? If not, I'll probably close it and take care of it myself at a later date.

Yep, go on. Unfortunately it has conflicts yet, but I have no free time to dig inside 🤷‍♂️

U can still fork my fork to make it work 😎

**P.S.** Lemme know if U need some help with that ℹ️

**Comment by codebycliff** [comment]
Sounds good. I'm going to close this for now and take a more incremental approach. Thanks for the initial work and sorry it didn't end up making it through.

**Pull request closed without merging**
