### PR TITLE
Support Rails::API controllers

### PR DESCRIPTION
**Pull request by seanlinsley**
#753

### CODE REVIEW

**Comment by bdmac** [comment]
Unfortunately I get the same error on this branch.
```
/Users/bdmac/.gem/ruby/2.3.0/bundler/gems/draper-d19c7f4fedbf/lib/draper/view_context.rb:8:in `view_context': super: no superclass method `view_context' for #<ApplicationController:0x007fc8997cf718> (NoMethodError)
Did you mean?  view_runtime
	from /Users/bdmac/.gem/ruby/2.3.0/bundler/gems/draper-d19c7f4fedbf/lib/draper/railtie.rb:55:in `block in <class:Railtie>'
	from /Users/bdmac/.gem/ruby/2.3.0/gems/railties-5.0.0/lib/rails/railtie.rb:226:in `block in run_console_blocks'
	from /Users/bdmac/.gem/ruby/2.3.0/gems/railties-5.0.0/lib/rails/railtie.rb:247:in `each'
	from /Users/bdmac/.gem/ruby/2.3.0/gems/railties-5.0.0/lib/rails/railtie.rb:247:in `each_registered_block'
	from /Users/bdmac/.gem/ruby/2.3.0/gems/railties-5.0.0/lib/rails/railtie.rb:226:in `run_console_blocks'
	from /Users/bdmac/.gem/ruby/2.3.0/gems/railties-5.0.0/lib/rails/application.rb:463:in `block in run_console_blocks'
	from /Users/bdmac/.gem/ruby/2.3.0/gems/railties-5.0.0/lib/rails/engine/railties.rb:13:in `each'
	from /Users/bdmac/.gem/ruby/2.3.0/gems/railties-5.0.0/lib/rails/engine/railties.rb:13:in `each'
	from /Users/bdmac/.gem/ruby/2.3.0/gems/railties-5.0.0/lib/rails/application.rb:463:in `run_console_blocks'
	from /Users/bdmac/.gem/ruby/2.3.0/gems/railties-5.0.0/lib/rails/engine.rb:442:in `load_console'
	from /Users/bdmac/.gem/ruby/2.3.0/gems/railties-5.0.0/lib/rails/commands/console.rb:34:in `initialize'
	from /Users/bdmac/.gem/ruby/2.3.0/gems/railties-5.0.0/lib/rails/commands/console_helper.rb:9:in `new'
	from /Users/bdmac/.gem/ruby/2.3.0/gems/railties-5.0.0/lib/rails/commands/console_helper.rb:9:in `start'
	from /Users/bdmac/.gem/ruby/2.3.0/gems/railties-5.0.0/lib/rails/commands/commands_tasks.rb:78:in `console'
	from /Users/bdmac/.gem/ruby/2.3.0/gems/railties-5.0.0/lib/rails/commands/commands_tasks.rb:49:in `run_command!'
	from /Users/bdmac/.gem/ruby/2.3.0/gems/railties-5.0.0/lib/rails/commands.rb:18:in `<top (required)>'
	from bin/rails:4:in `require'
	from bin/rails:4:in `<main>'
```

**Comment by mabdelfattah** [comment]
So, any solutions for this rails console problem?

**Comment by jpettettphaxio** [comment]
Including `ActionView::Rendering` in `ApplicationController` fixes this problem.  However, it appears to break `render :json`: rails/rails#27211

**Comment by jpettettphaxio** [comment]
Alternate solution, which doesn't break `render :json` (and works on master branch): put the following in ApplicationController:

```ruby
alias _orig_render_to_body render_to_body
include ActionView::Rendering
alias render_to_body _orig_render_to_body
```

**Comment by codebycliff** [comment]
This pull request was extracted into a few other pull requests:

[Issue 725: Remove conflicting source alias](https://github.com/drapergem/draper/pull/786)
[Remove previously deprecated functionality](https://github.com/drapergem/draper/pull/785)

The Rails API controller support will come through a combination of [being able to customize the default controller](https://github.com/drapergem/draper/pull/788) and a [work around documented in the README]()

**Pull request closed without merging**
