### PR TITLE
Release 3.0.0

### PR DESCRIPTION
**Pull request by codebycliff**
Contains version bump for release 3.0.0. The changelog could use more details if there are some.

### CODE REVIEW

**Comment by codebycliff** [comment]
Referencing issue here: https://github.com/drapergem/draper/issues/777

**Comment by codebycliff** [comment]
Actually, would we want to get some of these breaking changes in before we release a major version?

[Rename `UninferrableSourceError` to `UninferrableObjectError`](https://github.com/drapergem/draper/pull/768/files)
[Remove conflicting `source` alias](https://github.com/drapergem/draper/issues/725)

**Comment by syguer** [comment]
#768 has compatibility, so it can includes.
I think #725 looks better to fix before upgrade to major version. Because next major version will release after long time 🤔

**Comment by codebycliff** [comment]
I have added both pull requests to the [3.0.0 milestone](https://github.com/drapergem/draper/milestone/1). My plan is to track all changes for 3.0.0 within this milestone. If you see something else you feel should make it into the release, please comment here and I'll add it.

As far as 
https://github.com/drapergem/draper/pull/768, I was thinking about removing the compatibility with it as well and note it as a breaking change. Does anybody see an issue with doing so?

**Comment by syguer** [comment]
Should we fix this? https://github.com/drapergem/draper/issues/773

**Comment by codebycliff** [comment]
I haven't had a chance to verify it's reproducible. Once it's verified, I'll add it to the 3.0.0 milestone. If you want to take a stab at verifying / fixing it, that would be great. Otherwise, I'll get to it once I get a few more pressing things merged.

**Comment by dgmora** [comment]
Hi guys, thanks a ton for the gem! 

I just wanted to ask, will 3.0 be released soon?
We are running draper `3.0.0.pre1`, and we wanted to update to rails 5.1, but draper pre1 does not work well with 5.1. 

If it still takes some time, maybe a 3.0.0.pre2 would make sense, as the previous one was release in july last year. I know we have the option of using github as the source, but having a release would be better.

Cheers

**Comment by codebycliff** [comment]
I planned to cut a release here at RailsConf, however, it's looking more like next week. I should have 3.0.0 on RubyGems by the end of next week.

**Comment by IvanShamatov** [comment]
Sorry for disturbing again, @codebycliff. Are there any issues stops you from making release? Anything I can I help with? Thank you.

**Comment by codebycliff** [comment]
@IvanShamatov Nope, no issues. I just wanted to make sure I'd be around after the release to fix issues that may arise. I should have the release out this morning.

**Comment by codebycliff** [comment]
Release 3.0.0 has been pushed to RubyGems 🎉 . Please report any issues you may come across.

**Pull request merged**
