### PR TITLE
Activerecord relations

### PR DESCRIPTION
**Pull request by donaldpiret**
Better handling of activerecord relations. One can now call the decorator anywhere in the scope chain, and keep your relation decorated. Once you call methods that access individual records or arrays of records it automatically converts your result to a collection decorator or a regular decorator.

Would love to get some feedback on this.

### CODE REVIEW

**Comment by chibicode** [comment]
`.idea` directory should probably be removed :)

**Comment by donaldpiret** [comment]
Done!

**Comment by jcasimir** [comment]
I'm interested in this. Let's see if we can get it passing on CI.

**Comment by donaldpiret** [comment]
I'll try to spend some time on this tomorrow to bring it up to date. Using my branch in production so would love to see it merged in as well.

**Comment by donaldpiret** [comment]
Getting one failure with mongoid. Not super familiar with it so might take me a little bit of time to get around.

**Comment by donaldpiret** [comment]
Closing in favor of cleaned up version: #662

**Comment by saneshark** [comment]
:+1: @donaldpiret, DecoratorRelation will be able to do `delegate_all`, yes? Otherwise this would be a problem for say, pagination params that are only part of the CollectionProxy object. Currently CollectionDecorator does not allow `delegate_all`

**Comment by saneshark** [comment]
Could use some README documentation.

**Pull request closed without merging**
