### PR TITLE
Rails5 compatibility

### PR DESCRIPTION
**Pull request by kbrock**
Here are the changes we use locally.

They may not solve every draper issue, but they should work across all versions and I was hoping we could get this first batch in.

Thanks,

PS. this builds on some entries from #737 -- I tried to include attribution where posisble

### CODE REVIEW

**Comment by djberg96** [comment]
@kbrock Not sure I understand the build failure. What bundler just having a bad day, or does the travis.yml file need tweaking?

**Comment by DexterTheDragon** [comment]
Travis has a really old version of bundler installed by default. Adding the following to your travis.yml will probably fix it.

```yaml
before_install:
  - gem update bundler
```

**Comment by djberg96** [comment]
@DexterTheDragon Now we're seeing all kinds of (seemingly) unrelated errors.

**Comment by DexterTheDragon** [comment]
Looks like various errors in the test suite between all the different versions. I would bet that even the master branch doesn't pass now. If you look at the output from the last time the master branch was tested ( https://travis-ci.org/drapergem/draper/jobs/56058601 ), it was using capybara 2.4.4. Now it's using capybara 2.7.1 which probably needs a change in configuration.

**Comment by djberg96** [comment]
@DexterTheDragon It looks like there hasn't been an update on master in over a year. Doesn't bode well.

**Comment by seanlinsley** [comment]
@djberg96 I recently gained commit access to Draper, to get it working with Rails 5 🙌

**Comment by djberg96** [comment]
@seanlinsley Any updates?

**Comment by seanlinsley** [comment]
In #752 I've put together all the changes necessary to get Draper working with Rails 5. It would be appreciated if everyone could test it out in their apps and report any issues you find :octocat:

**Comment by kbrock** [comment]
thanks @seanlinsley

**Pull request closed without merging**
